services:
  - type: web
    name: ceexperimentapp-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FRONTEND_URL
        value: https://ceexperimentapp-frontend.onrender.com

  - type: web
    name: ceexperimentapp-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://ceexperimentapp-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
